# where things are
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir:    ./_data

# handling reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# filtering content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# plugins
whitelist: []
gems:      []

# conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "/ahm18.neic.nordforsk.org"

# outputting
timezone:  null
quiet:    false

# https://github.com/jekyll/jekyll/issues/302
permalink: pretty
defaults:
  -
    scope:
      type: "pages"
    values:
      permalink: /:path/:basename/


# conversion
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'codehilite'

include: []

collections:
  tutorials:
    output: true 
  crossteams:
    output: true

theme: jekyll-theme-cayman
